
package modificador.vista;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import modificador.modelo.FechaHoraSistema2;

/**
 *
 * @author Vicente Martinez Franco - Alberto Gil Valverde
 */
public class VistaModificador2 extends javax.swing.JFrame {

    
    private ControladorModificador2 micontrol;
    private FechaHoraSistema2 mimodelo;
    /**
     * Creates new form VistaModificador
     */
    public VistaModificador2() {
        initComponents();
        setLocationRelativeTo(null);
        //errorLabel.setVisible(false);
        mimodelo = new FechaHoraSistema2();
        micontrol = new ControladorModificador2(this, mimodelo);
        actualizar();
        errorLabel.setVisible(false);
        deshacerButton.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minutosText = new javax.swing.JTextField();
        cambiarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        dpLabel = new javax.swing.JLabel();
        diaLabel = new javax.swing.JLabel();
        mesLabel = new javax.swing.JLabel();
        añoLabel = new javax.swing.JLabel();
        diaText = new javax.swing.JTextField();
        mesComboBox = new javax.swing.JComboBox();
        añoText = new javax.swing.JTextField();
        horaLabel = new javax.swing.JLabel();
        minutosLabel = new javax.swing.JLabel();
        horaText = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        deshacerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        minutosText.setText("00");
        minutosText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cambiarButton.setText("Cambiar");
        cambiarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarButtonActionPerformed(evt);
            }
        });

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        dpLabel.setText(":");

        diaLabel.setText("Dia");

        mesLabel.setText("Mes");

        añoLabel.setText("Año");

        diaText.setText("1");
        diaText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        mesComboBox.setBorder(null);

        añoText.setText("2015");
        añoText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        horaLabel.setText("Hora");

        minutosLabel.setText("Minutos");

        horaText.setText("00");
        horaText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        errorLabel.setText("Error");

        deshacerButton.setText("Deshacer");
        deshacerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshacerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(diaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(mesLabel)
                        .addGap(50, 50, 50)
                        .addComponent(añoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diaText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(horaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(horaText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(dpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(minutosText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addComponent(errorLabel))
                                    .addComponent(minutosLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(añoText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cambiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deshacerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesLabel)
                    .addComponent(añoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minutosLabel)
                    .addComponent(horaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minutosText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpLabel)
                    .addComponent(errorLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deshacerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarButtonActionPerformed
       
        try{
            
            micontrol.cambiar();
            deshacerButton.setEnabled(true);
            
       }catch(NumberFormatException e){
           
            saltaError("no es un numero");
        }
        catch(Exception e){
            
            saltaError(e.getMessage());

        }
       
        
        
        
    }//GEN-LAST:event_cambiarButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        
        micontrol.salir();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void deshacerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deshacerButtonActionPerformed
        
        micontrol.deshacer();
        if(!mimodelo.puedeDeshacer())deshacerButton.setEnabled(false);
    }//GEN-LAST:event_deshacerButtonActionPerformed

    public void saltaError(String message){
        
        errorLabel.setText(message);
        errorLabel.setVisible(true);
        
        //dependiendo de donde este el error ponemos el borde del respectivo campo de texto en rojo
        switch(message){
            
            case("hora incorrecta"):
                horaText.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000")));
                break;
            case("minutos incorrectos"):
                minutosText.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000")));
                break;
            case("año incorrecto"):
                añoText.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000")));
                break;
            case("dia incorrecto"):
                diaText.setBorder(BorderFactory.createLineBorder(Color.decode("#FF0000")));
                break;
        }
        
    }
    
    public void actualizar(){

        //actualizamos el valor de los campos año mes dia hora y minutos
        
        añoText.setText(String.valueOf(mimodelo.getAño()));
        mesComboBox.setSelectedIndex(mimodelo.getMes());
        diaText.setText(String.valueOf(mimodelo.getDia()));
        horaText.setText(String.valueOf(mimodelo.getHora()));
        minutosText.setText(String.valueOf(mimodelo.getMinutos()));
        
        errorLabel.setText("Fecha modificada");
        errorLabel.setVisible(true);
        
        horaText.setBorder(BorderFactory.createLineBorder(Color.decode("#000000")));
        minutosText.setBorder(BorderFactory.createLineBorder(Color.decode("#000000")));
        diaText.setBorder(BorderFactory.createLineBorder(Color.decode("#000000")));
        añoText.setBorder(BorderFactory.createLineBorder(Color.decode("#000000")));
    }
    
    
    
    public String getAño() {
        return añoText.getText();
    }
    
    public int getMes(){
        
        return mesComboBox.getSelectedIndex();
    }
    public String getDia() {
        return diaText.getText();
    }

    public String getHora() {
        return horaText.getText();
    }

    public String getMinutos() {
        return minutosText.getText();
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel añoLabel;
    private javax.swing.JTextField añoText;
    private javax.swing.JButton cambiarButton;
    private javax.swing.JButton deshacerButton;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JTextField diaText;
    private javax.swing.JLabel dpLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JTextField horaText;
    private javax.swing.JComboBox mesComboBox;
    private javax.swing.JLabel mesLabel;
    private javax.swing.JLabel minutosLabel;
    private javax.swing.JTextField minutosText;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
