/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor.vista;
import conversor.modelo.Modelo;
/**
 *
 * @author Vicente
 */
public class VistaTemperatura extends javax.swing.JFrame {
    private ControladorTemperatura control;
    private Modelo modelo;

    /**
     * Creates new form VistaTemperatura
     */
    public VistaTemperatura() {
        initComponents();
        modelo=new Modelo();
        control=new ControladorTemperatura(this,modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        centigrados = new javax.swing.JTextField();
        farenheit = new javax.swing.JTextField();
        boton_convertir_centigrados = new javax.swing.JButton();
        boton_salir = new javax.swing.JButton();
        boton_convertir_farenheit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Centigrados");

        jLabel2.setText("Farenheit");

        centigrados.setText("0");

        farenheit.setText("-32");

        boton_convertir_centigrados.setText("Convertir C");
        boton_convertir_centigrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_convertir_centigradosActionPerformed(evt);
            }
        });

        boton_salir.setText("Salir");
        boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_salirActionPerformed(evt);
            }
        });

        boton_convertir_farenheit.setText("Convertir F");
        boton_convertir_farenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_convertir_farenheitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boton_convertir_centigrados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton_convertir_farenheit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_salir))
                    .addComponent(centigrados)
                    .addComponent(farenheit))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(centigrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(farenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_convertir_centigrados)
                    .addComponent(boton_salir)
                    .addComponent(boton_convertir_farenheit))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_salirActionPerformed
        control.salir();
    }//GEN-LAST:event_boton_salirActionPerformed

    private void boton_convertir_centigradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_convertir_centigradosActionPerformed
        control.convertirCent();
    }//GEN-LAST:event_boton_convertir_centigradosActionPerformed

    private void boton_convertir_farenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_convertir_farenheitActionPerformed
        control.convertirFar();
    }//GEN-LAST:event_boton_convertir_farenheitActionPerformed
    
    public double getCentigrados(){
        double cent;
        cent=Double.valueOf(centigrados.getText());
        return cent;
    }
    
    public double getFarenheit(){
        double far;
        far=Double.valueOf(farenheit.getText());
        return far;
    }
    
    public void actualiza(){
        centigrados.setText(String.valueOf(modelo.getCentigrados()));
        farenheit.setText(String.valueOf(modelo.getFarenheit()));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_convertir_centigrados;
    private javax.swing.JButton boton_convertir_farenheit;
    private javax.swing.JButton boton_salir;
    private javax.swing.JTextField centigrados;
    private javax.swing.JTextField farenheit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
